version: '3.8'

services:
  # PostgreSQL with pgvector for testing
  postgres-test:
    image: pgvector/pgvector:pg15
    container_name: orquel-test-db
    environment:
      POSTGRES_DB: orquel_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d orquel_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - orquel-test

  # Redis for caching tests (future use)
  redis-test:
    image: redis:7-alpine
    container_name: orquel-test-redis
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    command: redis-server --requirepass test123
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "test123", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - orquel-test

volumes:
  postgres_test_data:

networks:
  orquel-test:
    driver: bridge